import {useEffect,useMemo,useState} from 'react';
import AppV13 from './AppV13';
import './v14.css';

type P={first?:string;magic?:string;house?:string;year?:number;points?:number;wandWood?:string;wandCore?:string;patronus?:string;favoriteSubject?:string;options?:string[];completed?:string[];scores?:Record<string,number>;history?:string[]};
type Screen='home'|'subjects'|'agenda'|'mail'|'profile'|'house'|'bulletin'|'library'|'settings';
const fallback:P={first:'Killian',house:'Serdaigle',year:1,points:0,patronus:'Non révélé',favoriteSubject:'Défense contre les forces du Mal',options:[]};
const rooms=[['✦','Tour d’Astronomie','Bientôt'],['🛡','Salle de Défense','Disponible'],['⚗','Salle des Potions','Bientôt'],['⌂','Bibliothèque','Bientôt'],['♜','Grande Salle','Vie scolaire'],['❧','Serres de Botanique','Bientôt']];
const nav:[string,string,Screen][]=[['⌂','Accueil','home'],['▤','Matières','subjects'],['▦','Agenda','agenda'],['✉','Courrier','mail'],['●','Profil','profile'],['♜','Maison','house'],['▥','Bulletin','bulletin'],['▥','Bibliothèque','library'],['⚙','Paramètres','settings']];
const subjects=[['🛡','Défense contre les forces du Mal','Gilderoy Lockhart · 1re année'],['✦','Sortilèges','Filius Flitwick'],['⚗','Potions','Severus Rogue'],['◇','Métamorphose','Minerva McGonagall'],['❧','Botanique','Pomona Chourave'],['✧','Astronomie','Aurora Sinistra'],['⌛','Histoire de la magie','Cuthbert Binns'],['➳','Vol sur balai','Rolanda Bibine']];
function getProfile():P{try{return {...fallback,...JSON.parse(localStorage.getItem('academie-profile')||'{}')}}catch{return fallback}}

export default function AppV14(){
 const[loading,setLoading]=useState(true);const[course,setCourse]=useState(false);const[screen,setScreen]=useState<Screen>('home');const[p]=useState<P>(getProfile);
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),1500);return()=>clearTimeout(t)},[]);
 const name=p.magic||p.first||'Élève';const completed=p.completed?.length||0;const avg=useMemo(()=>{const a=Object.values(p.scores||{});return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0},[p.scores]);
 if(course)return <AppV13 startDfcm onReturn={()=>{setCourse(false);setScreen('home')}}/>;
 if(loading)return <div className="v14-loader"><div className="load-moon"/><div className="load-castle"/><div className="load-broom">➳</div><h1>Académie magique</h1><p>Les portes du château s’ouvrent…</p></div>;
 const go=(s:Screen)=>{setScreen(s);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="v14-app">
  <aside className="v14-side"><div className="v14-brand"><span>♜</span><b>ACADÉMIE<br/>MAGIQUE</b></div><nav>{nav.map(([ico,label,target])=><button key={label} className={screen===target?'active':''} onClick={()=>go(target)}><span>{ico}</span>{label}</button>)}</nav><div className="v14-values">SAGESSE<br/>APPRENTISSAGE<br/>COURAGE</div></aside>
  <div className="v14-main">
   <header className="v14-top"><button className="v14-mini-brand" onClick={()=>go('home')}>♜ Académie magique</button><div><button onClick={()=>go('mail')}>✉ <span>Courrier</span><b>3</b></button><button onClick={()=>go('agenda')}>▦ <span>Agenda</span></button><button className="student" onClick={()=>go('profile')}>◉ <span>{name}<small>{p.house||'Serdaigle'}</small></span></button></div></header>
   {screen==='home'?<Home name={name} p={p} avg={avg} completed={completed} go={go} openCourse={()=>setCourse(true)}/>:<SubPage screen={screen} name={name} p={p} avg={avg} completed={completed} go={go} openCourse={()=>setCourse(true)}/>} 
  </div>
 </div>
}

function Home({name,p,avg,completed,go,openCourse}:{name:string;p:P;avg:number;completed:number;go:(s:Screen)=>void;openCourse:()=>void}){return <>
 <section className="v14-world"><div className="v14-moon"/><div className="v14-cloud c1"/><div className="v14-cloud c2"/><div className="v14-castle"/><div className="v14-welcome"><span>PREMIÈRE ANNÉE · ACADÉMIE MAGIQUE</span><h1>Bonsoir,<br/><em>{name}.</em></h1><blockquote>« Ce que nous apprenons avec plaisir,<br/>nous ne l’oublions jamais. »</blockquote></div></section>
 <section className="v14-dashboard"><div className="v14-center"><div className="v14-cardrow">
  <article><small>PROCHAIN EN AGENDA</small><h3>Vol sur balai</h3><p>14h00 — Terrain de vol</p><button onClick={()=>go('agenda')}>Voir mon emploi du temps →</button></article>
  <article><small>PROCHAIN COURS</small><h3>Défense contre les forces du Mal</h3><p>Cours 1 — Qu’appelle-t-on les forces du Mal ?</p><button onClick={openCourse}>Reprendre le cours →</button></article>
  <article><small>NOUVEAUX MESSAGES</small><h3>Prof. Remus Lupin</h3><p>« N’oubliez pas : l’observation précède l’action. »</p><button onClick={()=>go('mail')}>Lire mes messages →</button></article>
  <article><small>POINTS DE MAISON</small><div className="points"><span>♜</span><strong>{p.points||0}</strong></div><p>{p.house||'Serdaigle'} · classement en cours</p><button onClick={()=>go('house')}>Voir la maison →</button></article>
 </div>
 <section className="v14-map"><header><small>EXPLORER L’ACADÉMIE</small><h2>Le château devient votre carte</h2></header><div className="v14-mapscene"><div className="map-castle"/>{rooms.map(([ico,label,status],i)=><button key={label} className={'room r'+i} onClick={()=>label==='Salle de Défense'?openCourse():label==='Bibliothèque'?go('library'):undefined}><b>{ico} {label}</b><span>{status}</span></button>)}</div></section>
 <section className="v14-year"><div><small>ANNÉE SCOLAIRE</small><b>Premier trimestre</b></div><div className="yearline"><i/><i/><i/><i/></div><div><small>PROCHAINE PAUSE</small><b>Fin du trimestre dans 32 jours</b></div></section></div>
 <aside className="v14-right"><section className="profilecard"><small>MON PROFIL</small><div className="avatar">{name.slice(0,1).toUpperCase()}</div><h2>{name}</h2><p>{p.house||'Serdaigle'} · {p.year||1}re année</p><dl><dt>Niveau</dt><dd>{p.year||1}re année</dd><dt>Baguette</dt><dd>{p.wandWood||'À renseigner'}{p.wandCore?` · ${p.wandCore}`:''}</dd><dt>Patronus</dt><dd>{p.patronus||'Non révélé'}</dd><dt>Matière préférée</dt><dd>{p.favoriteSubject||'À choisir'}</dd><dt>Cours validés</dt><dd>{completed}</dd><dt>Moyenne</dt><dd>{avg}%</dd></dl><button onClick={()=>go('profile')}>Voir mon profil complet →</button></section><section className="challengecard"><small>PROCHAINS DÉFIS</small><article><b>🛡 Terminer DCFM — Cours 1</b><p>Qu’est-ce que les forces du Mal ?</p><div><i style={{width:`${Math.max(8,completed*10)}%`}}/></div></article><article><b>▤ Lire le chapitre</b><p>Manuel de défense élémentaire</p></article><article><b>➳ Devoir : Sortilèges</b><p>Répéter Wingardium Leviosa</p></article><button onClick={()=>go('subjects')}>Voir tous mes défis →</button></section></aside></section></>}

function SubPage({screen,name,p,avg,completed,go,openCourse}:{screen:Screen;name:string;p:P;avg:number;completed:number;go:(s:Screen)=>void;openCourse:()=>void}){
 const title={subjects:'Matières',agenda:'Emploi du temps',mail:'Courrier',profile:'Profil de l’élève',house:`Maison ${p.house||'Serdaigle'}`,bulletin:'Bulletin scolaire',library:'Bibliothèque',settings:'Paramètres',home:''}[screen];
 return <main className="v14-sub"><button className="v14-back" onClick={()=>go('home')}>← Retour au tableau de bord</button><header><small>ACADÉMIE MAGIQUE · PREMIÈRE ANNÉE</small><h1>{title}</h1></header>
 {screen==='subjects'&&<div className="v14-subgrid">{subjects.map(([ico,s,t],i)=><article key={s}><span>{ico}</span><h2>{s}</h2><p>{t}</p>{i===0?<button onClick={openCourse}>Entrer dans la salle →</button>:<small>Programme disponible dans le cursus</small>}</article>)}</div>}
 {screen==='agenda'&&<section className="v14-paper"><h2>Cette semaine</h2>{[['Lundi','Sortilèges · 09h00'],['Mardi','Potions · 10h30'],['Mercredi','Métamorphose · 09h00'],['Jeudi','Défense contre les forces du Mal · 11h00'],['Jeudi','Astronomie · 21h00'],['Vendredi','Vol sur balai · 14h30']].map(([d,c])=><div className="v14-row" key={d}><b>{d}</b><span>{c}</span></div>)}</section>}
 {screen==='mail'&&<div className="v14-subgrid mail">{[['La Direction','Bienvenue à l’Académie','Votre dossier est enregistré et votre maison a été prévenue de votre arrivée.'],['Remus Lupin','Avant votre prochaine séance','L’observation précède toujours l’action. Prenez le temps d’identifier une menace avant de choisir votre défense.'],['Filius Flitwick','Un conseil de précision','Ne cherchez jamais la puissance avant la précision.']].map(([a,s,b])=><article key={s}><small>{a}</small><h2>{s}</h2><p>{b}</p></article>)}</div>}
 {screen==='profile'&&<section className="v14-profilefull"><div className="avatar big">{name[0]}</div><div><h2>{name}</h2><p>{p.house||'Serdaigle'} · {p.year||1}re année</p><dl><dt>Baguette</dt><dd>{p.wandWood||'À renseigner'} {p.wandCore||''}</dd><dt>Patronus</dt><dd>{p.patronus||'Non révélé'}</dd><dt>Matière préférée</dt><dd>{p.favoriteSubject||'À choisir'}</dd><dt>Cours validés</dt><dd>{completed}</dd><dt>Moyenne générale</dt><dd>{avg}%</dd><dt>Options futures</dt><dd>{p.options?.join(', ')||'Non choisies'}</dd></dl></div></section>}
 {screen==='house'&&<section className="v14-house"><div className="housecrest">♜</div><h2>{p.house||'Serdaigle'}</h2><strong>{p.points||0} points</strong><p>Curiosité · intelligence · créativité</p><div className="house-ranking"><span>1. Poufsouffle — 184</span><span>2. Gryffondor — 162</span><span>3. {p.house||'Serdaigle'} — {p.points||0}</span><span>4. Serpentard — 121</span></div></section>}
 {screen==='bulletin'&&<section className="v14-paper"><h2>Résultats de première année</h2>{['Sortilèges','Potions','Défense contre les forces du Mal','Métamorphose','Botanique','Astronomie','Histoire de la magie','Vol sur balai'].map(s=><div className="v14-row" key={s}><b>{s}</b><span>En attente</span></div>)}</section>}
 {screen==='library'&&<div className="v14-subgrid"><article><span>▤</span><h2>Manuel de défense élémentaire</h2><p>Lectures liées au premier cours de DCFM.</p><button onClick={openCourse}>Commencer la lecture →</button></article><article><span>✦</span><h2>Précis des sortilèges</h2><p>Fondements, gestes et prononciation.</p><small>Disponible prochainement</small></article><article><span>⚗</span><h2>Premières potions</h2><p>Ingrédients, sécurité et préparation.</p><small>Disponible prochainement</small></article></div>}
 {screen==='settings'&&<section className="v14-paper"><h2>Préférences</h2><div className="v14-row"><b>Interface</b><span>Mode nocturne de l’Académie</span></div><div className="v14-row"><b>Progression</b><span>Sauvegarde locale active</span></div><div className="v14-row"><b>Version</b><span>V1.4</span></div></section>}
 </main>
}
