export type Subject={id:string;name:string;teacher:string;description:string;years:number[];sequences:Record<number,string[]>;featured?:number;skills:string[];ambience:string}
const seq=(items:string[])=>items;
export const subjects:Subject[]=[
 {id:'sortileges',name:'Sortilèges',teacher:'Filius Flitwick',description:'Maîtriser le geste, la voix et l’intention magique.',years:[1,2,3],featured:1,skills:['Concentration','Précision gestuelle','Incantation'],ambience:'Une salle lumineuse, emplie de plumes et de tintements.',sequences:{1:seq(['La baguette et son rôle','Posture et concentration','Gestes fondamentaux','Incantation et prononciation','Premiers sortilèges simples','Wingardium Leviosa I','Wingardium Leviosa II','Lumière et magie quotidienne','Sortilèges en situation','Examen']),2:seq(['Révisions et maîtrise','Sortilèges de mouvement','Enchantements ménagers','Contre-sorts','Précision','Duel encadré','Objets enchantés','Combinaisons','Mise en situation','Examen']),3:seq(['Techniques avancées','Concentration prolongée','Enchantements','Contre-enchantements','Mobilité','Duel','Créativité','Analyse','Parcours','Examen'])}},
 {id:'potions',name:'Potions',teacher:'Severus Rogue',description:'Transformer avec méthode, mesure et sang-froid.',years:[1,2,3],featured:1,skills:['Dosage','Sécurité','Diagnostic'],ambience:'Les cachots, le cuivre des chaudrons et les vapeurs ambrées.',sequences:{1:seq(['Introduction aux Potions','Matériel','Sécurité','Préparation des ingrédients','Dosage','Température','Potion contre les furoncles','Diagnostic d’erreur','Potion d’Oubli','Examen']),2:seq(['Révisions','Ingrédients actifs','Infusions','Antidotes','Textures','Conservation','Potion fortifiante','Diagnostic','Laboratoire','Examen']),3:seq(['Réactivité','Catalyseurs','Antidotes II','Précision','Substitutions','Contrôle','Projet','Diagnostic','Laboratoire','Examen'])}},
 {id:'dfcm',name:'Défense contre les forces du Mal',teacher:'Remus Lupin',description:'Observer une menace et choisir une défense proportionnée.',years:[1,2,3],featured:3,skills:['Sang-froid','Analyse de menace','Défense pratique'],ambience:'Une classe marquée par les créatures et les exercices pratiques.',sequences:{1:seq(['Principes de défense','Vigilance','Créatures mineures','Protections','Réaction','Observation','Contre-sort','Scénarios','Révision','Examen']),2:seq(['Menaces','Posture','Créatures','Boucliers','Réflexes','Analyse','Duel','Scénarios','Parcours','Examen']),3:seq(['Introduction à la défense pratique','Épouvantards','Riddikulus','Chaporouges','Kappas','Strangulots','Hinkypunks','Analyse de menace','Parcours pratique','Examen'])}},
 ...[['metamorphose','Métamorphose','Minerva McGonagall'],['botanique','Botanique','Pomona Chourave'],['astronomie','Astronomie','Aurora Sinistra'],['histoire','Histoire de la magie','Cuthbert Binns'],['vol','Vol sur balai','Rolanda Bibine']].map(([id,name,teacher])=>({id,name,teacher,description:'Fondements, pratique guidée et évaluation progressive.',years:id==='vol'?[1]:[1,2,3],skills:['Observation','Méthode'],ambience:'Une salle ancienne dédiée à la pratique.',sequences:{1:Array.from({length:10},(_,i)=>i===9?'Examen':`Séquence ${i+1}`),2:Array.from({length:10},(_,i)=>i===9?'Examen':`Séquence ${i+1}`),3:Array.from({length:10},(_,i)=>i===9?'Examen':`Séquence ${i+1}`)}}))
];
export const options=[['Arithmancie','Septima Vector','Logique, nombres et analyse — jamais une simple divination numérique.'],['Divination','Sybill Trelawney','Interpréter avec prudence : les données peuvent être insuffisantes.'],['Soins aux créatures magiques','Rubeus Hagrid','Observer les comportements, notamment ceux des Hippogriffes.'],['Étude des runes anciennes','Bathsheba Babbling','Déchiffrer méthodiquement les systèmes d’écriture.'],['Étude des Moldus','Charity Burbage','Comprendre technologies, institutions, objets et cultures sans caricature.']];
export const houses={Gryffondor:{values:'Courage · Audace · Initiative',color:'#8e3035'},Serdaigle:{values:'Intelligence · Curiosité · Créativité',color:'#315d89'},Poufsouffle:{values:'Loyauté · Travail · Patience',color:'#b8892b'},Serpentard:{values:'Ambition · Stratégie · Détermination',color:'#28634e'}} as const;
