import {useMemo,useState} from 'react';
import {ArrowLeft,BookOpen,CheckCircle2,ChevronRight,Eye,Shield,Skull,Star} from 'lucide-react';

const lessons=['Qu’appelle-t-on les forces du Mal ?','Observer avant d’affronter','Protection personnelle','Maléfices et contre-mesures','Créatures dangereuses','Objets ensorcelés','Peur et sang-froid','Fuite, protection ou intervention ?','Études de situations','Examen de première année'];
const portrait='https://commons.wikimedia.org/wiki/Special:FilePath/Kenneth%20Branagh%202010%20Comic-Con%20cropped.jpg?width=720';

type Props={onExit:()=>void};
export default function DfcmV13({onExit}:Props){
 const[view,setView]=useState<'subject'|'course'>('subject');
 const[step,setStep]=useState(0);const[answers,setAnswers]=useState<boolean[]>([]);const[choice,setChoice]=useState<number|null>(null);
 const score=useMemo(()=>answers.length?Math.round(answers.filter(Boolean).length/answers.length*100):0,[answers]);
 const answer=(ok:boolean)=>setAnswers(a=>[...a,ok]);
 if(view==='subject')return <div className="dfcm13"><header className="df-top"><button onClick={onExit}><ArrowLeft/> Académie</button><span>V1.3 · Défense</span></header><main>
  <section className="df-hero"><div className="df-sigil"><Shield/></div><div><p>MATIÈRE OBLIGATOIRE · PREMIÈRE ANNÉE</p><h1>Défense contre les forces du Mal</h1><h2>Comprendre le danger avant de chercher à le vaincre.</h2></div></section>
  <section className="teacher-card"><img src={portrait} alt="Kenneth Branagh, interprète de Gilderoy Lockhart"/><div><p className="kicker">VOTRE PROFESSEUR</p><h2>Gilderoy Lockhart</h2><p>Écrivain célèbre, décoré et extraordinairement sûr de lui. Son cours est volontairement théâtral : récits, démonstrations, mises en scène et situations imprévues. L’élève devra parfois distinguer ce que le professeur affirme de ce que l’observation permet réellement de conclure.</p><blockquote>« La première règle face au danger ? Savoir exactement ce que vous avez devant vous. La seconde ? Avoir une excellente présentation. »</blockquote><small>Portrait : Kenneth Branagh · Wikimedia Commons · CC BY-SA 2.0</small></div></section>
  <section className="df-intro"><p className="kicker">OBJECTIF DE L’ANNÉE</p><h2>Observer · juger · se protéger</h2><p>La Défense ne se réduit pas au duel. Elle apprend à reconnaître une menace, à comprendre son mode d’action, à conserver assez de sang-froid pour décider et à choisir une réponse proportionnée. En première année, la priorité est donc la prudence : identifier avant d’intervenir.</p><div className="skill-row"><span><Eye/> Observation</span><span><Shield/> Défense</span><span><Skull/> Identification</span><span><Star/> Jugement</span></div></section>
  <div className="df-lessons">{lessons.map((l,i)=><button key={l} disabled={i>0} onClick={()=>{setView('course');setStep(0)}} className={i===0?'ready':''}><b>{String(i+1).padStart(2,'0')}</b><div><small>{i===0?'Cours disponible':'À venir'}</small><h3>{l}</h3><p>{i===0?'Cours interactif · 15–20 min · théorie + décisions':'Se débloquera après la séquence précédente'}</p></div><ChevronRight/></button>)}</div>
 </main></div>;
 return <div className="dfcm13 lesson13"><header className="df-top"><button onClick={()=>setView('subject')}><ArrowLeft/> Première année</button><span>{step+1}/6</span></header><main>
  <div className="lesson-progress"><i style={{width:`${((step+1)/6)*100}%`}}/></div>
  {step===0&&<section className="chapter"><p className="kicker">COURS 1 · OUVERTURE</p><h1>Qu’appelle-t-on les forces du Mal ?</h1><div className="dialogue"><img src={portrait} alt="Gilderoy Lockhart"/><p><b>Lockhart</b>« Avant de combattre le Mal, encore faut-il éviter de prendre chaque ombre de couloir pour un mage noir. Sortez vos parchemins. Aujourd’hui, nous classons les menaces. »</p></div><p>Dans le monde magique, le mot « Mal » est commode mais imprécis. Une créature agressive, un objet maudit, un sort hostile et un sorcier malveillant peuvent tous représenter un danger, mais ils ne fonctionnent pas de la même manière. La première compétence défensive est donc une compétence de <strong>diagnostic</strong>.</p><p>Une défense efficace commence par trois questions : <strong>qu’est-ce qui constitue la menace ? comment agit-elle ? sur quoi puis-je agir sans aggraver la situation ?</strong> Cette méthode paraît moins spectaculaire qu’un duel, mais elle évite de répondre au mauvais problème.</p><div className="note"><BookOpen/><p><b>À retenir</b> Danger et intention ne sont pas synonymes. Une plante dangereuse n’est pas « mauvaise » ; un objet peut être ensorcelé sans volonté propre ; un adversaire humain peut, lui, adapter sa stratégie.</p></div></section>}
  {step===1&&<section className="chapter"><p className="kicker">CHAPITRE I</p><h1>Quatre familles de menace</h1><div className="threat-grid"><article><span>01</span><h3>Créature</h3><p>Elle possède un comportement, des instincts et parfois une intelligence. La défense passe d’abord par la connaissance de ses réactions.</p></article><article><span>02</span><h3>Objet ensorcelé</h3><p>Le danger vient d’un effet magique attaché à un support. Le toucher, le déplacement ou l’usage peuvent déclencher cet effet.</p></article><article><span>03</span><h3>Sort ou maléfice</h3><p>La menace est un effet magique actif. Il faut identifier sa nature, s’en protéger, l’interrompre ou en limiter les conséquences.</p></article><article><span>04</span><h3>Adversaire</h3><p>Un être capable d’intention peut observer votre réaction et changer de méthode. La situation devient stratégique.</p></article></div><div className="dialogue lockhart"><p><b>Lockhart</b>« Dans mes ouvrages, naturellement, j’ai rencontré les quatre. Souvent avant le déjeuner. Mais vous, commencez par apprendre à les distinguer. »</p></div></section>}
  {step===2&&<section className="chapter"><p className="kicker">EXERCICE · LE BUREAU INTERDIT</p><h1>Vous trouvez une boîte qui murmure votre nom.</h1><p>Elle repose seule sur un bureau. Personne ne semble la manipuler. Lorsque vous approchez la main, le couvercle vibre légèrement.</p><h3>Quelle est votre première décision ?</h3><div className="decision">{['Ouvrir rapidement pour identifier son contenu','Ne pas toucher, observer et prévenir un adulte compétent','Lancer immédiatement un sort offensif','La transporter dans le couloir pour mieux la voir'].map((x,i)=><button className={choice===i?'picked':''} onClick={()=>setChoice(i)} key={x}>{x}</button>)}</div>{choice!==null&&<div className={choice===1?'feedback good':'feedback bad'}>{choice===1?<><CheckCircle2/><p><b>Bonne démarche.</b> Les indices orientent vers un objet potentiellement ensorcelé. L’interaction elle-même peut être le déclencheur : observer sans toucher est donc la réponse la plus sûre.</p></>:<p><b>Lockhart lève un sourcil.</b> Vous agissez avant d’avoir compris le mécanisme. Dans une situation inconnue, augmenter les interactions augmente souvent le risque.</p>}</div>}</section>}
  {step===3&&<section className="chapter"><p className="kicker">CHAPITRE II · MÉTHODE</p><h1>La règle O.R.A.</h1><p>Pour donner une structure simple aux premières décisions, le cours utilise trois verbes : <strong>Observer, Reconnaître, Agir</strong>.</p><div className="ora"><article><b>O</b><h3>Observer</h3><p>Distance, traces, sons, mouvements, personnes présentes, changements récents. On collecte des faits avant des hypothèses.</p></article><article><b>R</b><h3>Reconnaître</h3><p>On rapproche les indices d’une catégorie de menace et on évalue ce qui reste inconnu. Savoir que l’on ne sait pas est une information utile.</p></article><article><b>A</b><h3>Agir</h3><p>On choisit l’action la moins risquée capable d’améliorer la situation : s’éloigner, protéger, alerter, neutraliser seulement si nécessaire.</p></article></div><p>Cette logique introduit une idée centrale de toute la première année : <strong>la meilleure défense n’est pas toujours un sort.</strong> La distance, l’environnement, l’aide d’un professeur ou le simple refus de toucher un objet peuvent constituer une défense supérieure à une intervention spectaculaire.</p></section>}
  {step===4&&<section className="chapter"><p className="kicker">ÉPREUVE RAPIDE</p><h1>Le portrait qui cligne des yeux</h1><p>Dans un couloir normalement vide, un portrait que vous n’avez jamais vu vous demande de vous approcher et promet de révéler un passage secret. Aucun autre élève ne semble le connaître.</p><div className="riddle"><p>Classez mentalement les informations :</p><button onClick={()=>answer(true)}>« Le portrait est inconnu » = fait observable</button><button onClick={()=>answer(false)}>« Il veut forcément me piéger » = fait observable</button><button onClick={()=>answer(true)}>« Je peux vérifier son existence auprès d’un professeur » = action prudente</button><button onClick={()=>answer(false)}>« Un passage secret est nécessairement dangereux » = certitude</button></div><p className="micro">Chaque clic enregistre votre jugement. Ici, certaines affirmations décrivent des faits ; d’autres ne sont encore que des hypothèses.</p></section>}
  {step===5&&<section className="chapter result13"><p className="kicker">FIN DU COURS 1</p><h1>Première règle : comprendre avant d’affronter.</h1><div className="score-orb">{answers.length?score:100}<small>%</small></div><p>Vous savez désormais distinguer plusieurs familles de menace et appliquer une première méthode de diagnostic. Le prochain cours approfondira l’observation : traces, incohérences, environnement et signaux faibles.</p><div className="teacher-final"><img src={portrait} alt="Gilderoy Lockhart"/><p><b>Lockhart</b>« Convenable. Vous n’avez pas encore mon instinct, évidemment, mais vous commencez à regarder dans la bonne direction. »</p></div><button className="gold13" onClick={()=>setView('subject')}>Retour au programme</button></section>}
  {step<5&&<button className="next13" disabled={step===2&&choice===null} onClick={()=>{if(step===2&&choice!==null)answer(choice===1);setStep(s=>s+1);window.scrollTo({top:0,behavior:'smooth'})}}>Continuer <ChevronRight/></button>}
 </main></div>;
}
